/* figures.js — Plotly interactive figure mounts
 * Data lives in js/data.js (auto-generated by generate_plotly_data.py)
 * Re-run that script whenever the source data changes.
 */
(function () {
  const CONFIG = {
    responsive: true,
    displayModeBar: true,
    displaylogo: false,
    modeBarButtonsToRemove: ['select2d', 'lasso2d', 'autoScale2d'],
    toImageButtonOptions: { format: 'png', scale: 2 }
  };

  function mountAll() {
    if (typeof NS_FIG_DATA === 'undefined') return;
    for (const [figId, data] of Object.entries(NS_FIG_DATA)) {
      const el = document.getElementById('fig-' + figId);
      if (!el) continue;
      Plotly.newPlot(el, data.traces, data.layout, CONFIG);
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mountAll);
  } else {
    mountAll();
  }
})();
